inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rake.yml
    - lib/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 2.7.1
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - smart_types.gemspec
    - bin/console

# NOTE: support for old ruby versions
Style/RedundantBegin:
  Enabled: false

# NOTE: used only in specs and it is ok in specs
Lint/EmptyBlock:
  Enabled: false

Layout/EmptyLines:
  AutoCorrect: true
